Repository automotiveMastermind/prompt, pull requests merged in 2018-03, with the labels that each got.

#10 feat(uname): add ubuntu 17.10 support
  bootstrap.sh
  src/scripts/add-bookmark.sh
  src/scripts/add-var.sh
  src/scripts/dotnet-install.sh
  src/scripts/git-extensions.sh
  src/scripts/git-extras.sh
  src/scripts/list-directory.sh
  src/scripts/open-url.sh
  src/scripts/remove-backup.sh
  src/scripts/remove-bookmark.sh
  src/scripts/remove-var.sh
  src/scripts/set-nvm.sh
  src/scripts/update-prompt.sh
  uname/install-Darwin.sh
  uname/install-debian.sh
  uname/install-fedora.sh
  uname/install-ubuntu.sh
Labels: enhancement, in progress, review

#11 docs: update readme
  README.md
Labels: in progress, review

#12 fix: prompt updates on sierra
  src/scripts/add-bookmark.sh
  src/scripts/add-var.sh
  src/scripts/dotnet-install.sh
  src/scripts/git-extensions.sh
  src/scripts/git-extras.sh
  src/scripts/open-url.sh
  src/scripts/post/post-update-prompt.sh
  src/scripts/remove-backup.sh
  src/scripts/remove-bookmark.sh
  src/scripts/remove-var.sh
  src/scripts/set-nvm.sh
  src/scripts/update-prompt.sh
  uname/install-Darwin.sh
Labels: bug, in progress, review
